title: My Hacker Blog
description: Terminal thoughts. Green text. No apologies.
author: shingamer

theme: jekyll-theme-hacker

markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
